### ISSUE TITLE
Feature Request: Accessibility Service + Draw Over

### ISSUE THREAD

**Issue by Saijin-Naib** [hegocre/NextcloudPasswords#22]
Password managers like BitWarden implement an Accessibility Service to enable save and load of passwords in more apps and websites.

I'm not able to use NextCloud Passwords in things like NextCloud OTP Manager app, or many other Android apps.

**Comment by hegocre** [comment]
Hello

I'm gonna need more info on that, I'm afraid I don't fully understand your request. Do you mean something like the Autofill Service, which allows you to fill passwords into other apps login forms / browser login forms? In that case, that is already implemented (at least, the autofill part, the save passwords part is a pending feature).

If you are not referring to this, I'm going to need more explanation.

Thanks!

**Comment by Saijin-Naib** [comment]
Here's the code for how BitWarden does it: 
https://github.com/search?q=repo%3Abitwarden%2Fmobile%20Accessibility&type=code

I'll attach a screenshot of how they describe it in the Android settings later.

All I know is that I could use BitWarden on any app or field without issue, and so far, I've been mostly unable to do the same with NextCloud Passwords, so I'm thinking this has something to do with it.

**Comment by hegocre** [comment]
Hi @Saijin-Naib 

I've taken a look into the Bitwarden app and its accessibility service, and it looks like it is an Autofill Service replacement oriented at older Android versions. The Autofill service should replace it. Could you tell me an example of a website/app where the autofill popup is not appearing? Some apps do not declare their fields/do not make them accessible.

Thanks

**Comment by Saijin-Naib** [comment]
Yes, I use Firefox now, and prior Edge. It looks like some browsers and password managers can declare an Assistant App capability which can allow them to handle Autofill in even more situations!

Quite confusing!

**Comment by hegocre** [comment]
Hi @Saijin-Naib, I've been working on a new version which should have better support for autofill in firefox. It would be great if you could test it. You can download the debug version in the [actions](https://github.com/hegocre/NextcloudPasswords/actions/runs/6838130696) tab.

Thank you!

**Comment by Saijin-Naib** [comment]
I really like the workflow of opening the app and having it switch back. This matches the UX of BitWarden's Autofill.

The password prompt overlay also doesn't seem to flicker as much, so that's great.

**Comment by Saijin-Naib** [comment]
Screenshot for how BitWarden describes their accessibility service
![Screenshot_20231111-135346](https://github.com/hegocre/NextcloudPasswords/assets/19295950/5caa424d-e690-4fc7-8bee-97fb107c6b64)

**Comment by hegocre** [comment]
Hi @Saijin-Naib 

Have you been using the autofill function? How is it working for you? Do you think it still needs an accessibility service, or does it work good enough?

Thank you!

**Comment by Saijin-Naib** [comment]
So far it has been great, but I'm also using it on an already setup device... I would have to reset my phone to really test and see what apps might need it.

**Comment by Saijin-Naib** [comment]
Hmmm, yes, I think those extra capabilities might be handy. I can't get NextCloud Passwords to show up on NextCloud Passwords Debug, nor can I force it by trying to tap and hold and call up the Autofill menu item.

**Comment by hegocre** [comment]
Good catch.

This has actually nothing to do with the autofill service, but with the text field not providing autofill hints, which means autofill services in general (not just this app) don't recognize the field as a password field, the same way they don't ask to field the WhatsApp message field, for example.

Will fix this

**Comment by hegocre** [comment]
I will consider this issue fixed. If more problems arise with the autofill service, which also happen with other apps (e.g. Bitwarden), feel free to reopen the issue and I will take a look into it

**Comment by Saijin-Naib** [comment]
https://play.google.com/store/apps/details?id=com.mohela.MOHELA

MOHELA no longer works with NC Passwords, and calling it manually by tapping/holding and choosing Autofill says contents cant be autofilled

**Comment by hegocre** [comment]
Hi @Saijin-Naib 

Just to be sure, could you check if it works with other autofill services like bitwarden?

For autofill to work, apps must declare text fields as user/passwords fields. If they don't, they are indistinguishable from a normal text field, like it could be the whatsapp message field.

Thank you!

**Comment by Saijin-Naib** [comment]
This is NC Password not recognizing the field, and not autofill upon demand. 

![ncpasswords](https://github.com/hegocre/NextcloudPasswords/assets/19295950/0b6dfd1d-7029-4a52-864f-157163cbe332)

This is KeepassDX autofilling
![keepassdx](https://github.com/hegocre/NextcloudPasswords/assets/19295950/0e1c4f46-bd4b-4c7c-a48b-5b3965f3a69d)

**Comment by hegocre** [comment]
Thank you! Then I will install the app myself and check why it is not being detected, see what can be done

**Comment by Saijin-Naib** [comment]
Thank you so much for such wonderful support!

**Comment by hegocre** [comment]
Hello,

I think I have found the problem, pushed a commit that should fix it. If you could confirm it now works on [CI #172](https://github.com/hegocre/NextcloudPasswords/actions/runs/7154768111), that would be great. 

Thanks!

**Comment by Saijin-Naib** [comment]
Unfortunately, no change. 
Still doesnt pop up, still cant force autofill. 

Also, trying to enable the pin on the debug build does not call up the keyboard when you tap on the field. 
![Screenshot_20231209-210352](https://github.com/hegocre/NextcloudPasswords/assets/19295950/eca98e6f-80f6-42a4-a593-edcb90e2cf5c)

**Comment by hegocre** [comment]
That is weird, because I previously had the same error, but now it is detecting the field just fine.

![Screenshot_20231210-030922.png](https://github.com/hegocre/NextcloudPasswords/assets/15657088/041beec3-4304-438f-a77e-3d913e8fce88)

Please, make sure to enable the autofill service on the debug version, which is not the same as the normal app.

Also, I'm afraid I don't fully understand the second issue you are exposing. Could you please explain it to me again?

Thank you!!

**Comment by Saijin-Naib** [comment]
It is enabled, but I dont think the keyboard autofill was a thing until Android 11 or later, and I have 10. Perhaps that is the difference? 
![Screenshot_20231209-210352](https://github.com/hegocre/NextcloudPasswords/assets/19295950/e20e7ecb-7503-4d67-bbdb-5573960b365f)
![Screenshot_20231209-211631](https://github.com/hegocre/NextcloudPasswords/assets/19295950/f02dcce6-bd00-452e-a31d-19bc4f7dbfe3)
![Screenshot_20231209-211642](https://github.com/hegocre/NextcloudPasswords/assets/19295950/29f8c97d-45e2-4873-a80b-58abf67a1ddd)

For the pin, the keyboard doesnt detect it as a text field so I can not type a pin:  
![Screenshot_20231209-212437](https://github.com/hegocre/NextcloudPasswords/assets/19295950/6c1e8ec1-ccc0-4023-9ad3-ab2afee5aefd)

**Comment by Saijin-Naib** [comment]
I'm also seeing that v1.06-debug(18) is not detecting field that stable does,  like paypal login within target app. 
![image1](https://github.com/hegocre/NextcloudPasswords/assets/19295950/93b58a4f-0469-44f4-9b35-fed4d4378935)

**Comment by hegocre** [comment]
I will test with an Android 10 device and see what is happening, but it is a bit weird, since I have changed nothing since the stable version that could result in less detections of fields. Did autofill with PayPal on the target app work before? Also, keyboard autofill not existing shouldn't be a problem, since it should then autofill with the popup. Either way, I'll take a look and see what I find in my end.

Also, about the PIN problem, could you please open a new issue, since it is unrelated to this, so we keep the repo better organized. Thanks!

**Comment by Saijin-Naib** [comment]
Yes, stable works correctly:  
![Screenshot_20231210-104933](https://github.com/hegocre/NextcloudPasswords/assets/19295950/676ac4d8-240f-45c1-8d30-29aba9ef5e21)

**Comment by hegocre** [comment]
Alright, so good news!

I have found the problem. The thing is, to detect if a field can be autofilled, and with which data, the autofill service relies on hints provided by app developers. Since (Android 13), Android automatically adds a hint if it does not exist, based on other field properties. This is NOT documented anywhere, but I found out by digging into the Android source code, which allowed me to replicate the behavior and get it working.

The issue with MOHELA should now be fixed. I don't know about the PayPal one, and I can't test is since the Target app is not available in my country, you tell me if it has been fixed.

Thank you!

**Comment by Saijin-Naib** [comment]
Will I need to test on Stable? 

Thanks so much! 

I will hopefully have Android 11+ phone for personal usage this week.

**Comment by hegocre** [comment]
If you can test on the debug build, it should work on stable as well. Had it working on an Android 10 emulator, but it would be nice if you could confirm as well. Thank you!

**Comment by hegocre** [comment]
Also, the keyboard problem seems to be related to a library update, the issue is supposed to be fixed on the next release, which shouldn't take long

**Comment by Saijin-Naib** [comment]
Target is fixed! 
![Screenshot_20231210-151155](https://github.com/hegocre/NextcloudPasswords/assets/19295950/940e6976-b664-4bc6-b664-3c30c8c00378)

MOHELA is not, but they are the worst.

**Comment by hegocre** [comment]
Hmm, it should work, it works on my device™. It was working on the A10 emulator.

Could you please:

* Open the debug version
* Go to the MOHELA app and trigger the autofill
* Go back to the debug version, go to the information screen, and long press the version field
* Send or attach the debug log here. Redact the sensitive information, if any, and if not sure, send privately.

Thanks!!

**Comment by Saijin-Naib** [comment]
Emailed, thank you again!

**Comment by hegocre** [comment]
What version are you running on now? I think it is possible that if you took the latest CI, you took the one related to translations, which means you got a version with no fixes implemented. Could you please be sure to download the debug app from [this run](https://github.com/hegocre/NextcloudPasswords/actions/runs/7159714165), so that you get the current version? Be sure to run on version v1.0.6-DEBUG (24).

Also, in case you have to take the logs again, please be sure to follow this workflow when capturing the log.

![ezgif-3-ee9fa92b0e](https://github.com/hegocre/NextcloudPasswords/assets/15657088/6e3e3fb8-ec06-4023-b4cf-776ae6460325)

Thank you!

**Comment by Saijin-Naib** [comment]
Using the right CI Artifact makes MOHELA work again! 

😑 Sorry

I will be setting up a phone from scratch under /e/OS Android 12 this week. 

If I come across more weird apps, what is the best way to report? All at once? One issue per?

**Comment by hegocre** [comment]
Great, thank you!

I'm thinking of enabling the GirHub discussions tab, and start a Discussion for reporting apps that don't work. I think it could be the best way to keep the Issues organized.
